### ISSUE TITLE
Update in Marketplace

### ISSUE THREAD

**Issue by tnonnenm** [myheritage/bitbucket-merge-checker#1]
Hi there,
we like this add on for bitbucket and use it in our project.
The server is maintained by administrators and they are very worried about the version the add on supports:

![image](https://user-images.githubusercontent.com/43718273/95086089-5d43bb80-0720-11eb-923f-029b1df75a5e.png)

Our server currently runs version 7.3.1 and the add on still works.
Is it possible to update the version in the market place to the latest the plugin really supports?

Thanks,
Thomas

**Comment by mbarzeev** [comment]
Hi @tnonnenm,
I've seen the add-on running on BitBucket server version 7.4.1 with flying colors, so there is no issue with it that version or previous versions I know of.
**Having said that**, you might have certain configurations or other modifications to your BitBucket server which might break it, or may break by it. I cannot guarantee it won't happen.
I would suggest to try it on a separate BitBucket server (the SDK provides easy means to install a "dummy" server for which you can determine the versions easily) and test it there.

Cheers
